### ISSUE TITLE
parser: lex & yacc (flex & bison) 내용 정리

### ISSUE THREAD

**Issue by namhyung** [swmaestro06-apus/apus#1]
lex 와 yacc 혹은 (flex 와 bison) 문서를 읽고 간단하게 wiki에 정리하기

**Comment by namhyung** [comment]
이론 부분은 어느 정도 정리되었고, 앞으로 예제를 조금 더 추가할 예정
https://github.com/swmaestro06-apus/apus/wiki/Lex-&-Yacc-%28flex-&-bison%29-%EB%82%B4%EC%9A%A9-%EC%A0%95%EB%A6%AC

**Comment by junghyun4425** [comment]
가장 아래쪽에 yacc과 lex로 만든 계산기 예제를 올렸습니다.
부족한 부분 알려주시면 수정하겠습니다.

**Comment by namhyung** [comment]
이정도면 좋은 것 같습니다. 혹시 빠진게 있으면 그때그때 업데이트 하면 되겠죠.
