### ISSUE TITLE
data type에 copy가 필요할 거 같네요..

### ISSUE THREAD

**Issue by jeongmincha** [swmaestro06-apus/apus#100]
하..ㅠㅠ 모든 경우를 미리 다 재보고 코드를 구현할 수 있었다면 좋았겠지만...
계속해서 새로운 문제가 보이네요

struct A {
    s16 a = 5
    s16 b = 7
    s16 c
    s16 d
}
A라고 하는 DataType안에 a,b,c,d라고 하는 DataType이 들어간 형태일겁니다.

원래 저희가 data type table에 primitive type들은 자주 사용되니깐 미리 추가하자는 식으로 구현을 하기로 했었는데요. c랑 d같은 경우 가리키는 DataType 인스턴스가 완전히 똑같아도 문제 없겠습니다만,
a랑 b같은 경우, 같은 타입이면서 primitive임에도 불구하고 초기화 expression이 5와 7로 서로 다릅니다.. 즉, a랑 b는 다른 DataType 인스턴스를 가리켜야 겠죠.

위 예는 간단히 primitive에 대해서 처리한 것이고 예를 들어서
struct B {
    struct A aa = {1,2,3,4}
    struct A bb = {5,6,7,8}
}
이렇게 짜여진 경우에는 struct A라는 데이터 타입을 복사한 후에 init expression을 다르게 갖는 인스턴스 aa, bb를 새로 만들어야 할 것입니다.

제가 봤을 땐 이런 상황 때문에 아무래도 Copy함수를 만들어야 할 거 같습니다.

**Comment by jeongmincha** [comment]
@namhyung 
읽어보시고 납득이 간다하면 이에 따라서 data type 코드를 수정하는 커밋을 추가하여 PR날리겠습니다.

**Comment by namhyung** [comment]
데이터 타입은 타입 정보 자체만을 가지므로 위의 경우에도 copy는 필요없지 않을까 생각됩니다. 다만 struct 데이터 타입에서 맵으로 name, DataType을 연결하는 대신 name, DataTypeWithInit (?) 정도의 클래스를 연결하도록 하고 DataTypeWithInit이 원래의 데이터 타입에 대한 참조와 초기값을 가지도록 하면 어떨까요?

**Comment by namhyung** [comment]
이슈를 별도로 분리하기 보다는 #75 에서 같이 논의하는게 좋을 것 같습니다.
