### ISSUE TITLE
폴더 디렉토리 구조 체계 수정 요구

### ISSUE THREAD

**Issue by jeongmincha** [swmaestro06-apus/apus#12]
@junghyun4425 
지금 src폴더 아래에 lex, yacc 파일이 바로 위치하게 되어 있고, 완전 메인에 Makefile이 위치하는 구조인데, 이게 한단계 아래의 하위 디렉토리로 이동하였으면 함.

일단 제가 생각하는 큰 디렉토리는
/gtest_src
/test
/include
/src
와 같이 폴더 체계가 잡히면 좋겠습니다. 1)vm이라던지 2) lex, yacc을 사용하는 부분도 src폴더 아래의 하위계층으로 존재하였으면 좋겠고, 최상위층에 존재하는 make파일이나 CMake파일은 나중에 최종적으로 우리 프로젝트의 실행 파일이 만들어지도록 하는 것이 좀 더 직관적일 거 같습니다.
1. gtest_src는 gtest.h와 gtest-all.cc 파일이 존재
2. test폴더 아래에 test를 위한 코드를 추가하면 됩니다. 
3. include폴더 아래에는 헤더파일들이 존재.
4. src폴더 아래에는 소스코드들이 존재. (소스 코드들 자체도 폴더를 계층화하여 더 자세히 분류할 것)

@namhyung 
현재 제가 pull request한 것은 gtest-1.7.0 하위에 있는 필요없는 파일도 다 들어있어서 상당히 비합리적인 부분이 많습니다. 제가 다시 폴더 디렉터리 구조 체계를 제대로 잡아서 다시 pull request하겠습니다.

**Comment by namhyung** [comment]
전체적으로 찬성합니다. 다만 gtest 부분은 test 폴더에 옮기는 것이 나을 것 같고, 그리고 개인적으로 폴더 이름은 소문자로 통일하는 것이 좋을 것 같습니다.

**Comment by namhyung** [comment]
적용됨
