### ISSUE TITLE
parser: expression 문법 추가

### ISSUE THREAD

**Issue by enghqii** [swmaestro06-apus/apus#14]
expression부분이 있어야 그와 관련된 추상 문법트리를 만들 수 있습니다.
@junghyun4425 @namhyung

**Comment by namhyung** [comment]
@enghqii 커밋과 마찬가지로 이슈작성 시에도 제목에 좀 더 신경써 주시기 바랍니다. 제목은 "subsystem: message" 형식으로 30자 내외의 간략한 형태로 작성해 주시고, 보다 자세한 설명은 본문에 적는 습관을 가집시다.

@junghyun4425 저번에 작업하던 소스 빨리 정리해서 PR 보내주세요.

**Comment by namhyung** [comment]
@junghyun4425 지금 push 해 둔 브랜치를 살펴보았는데, array나 assignment 쪽은 아직 작업할 부분이 남은 것 같으니 일단 제외시키고 기본 expression 추가한 커밋들만 따로 빼서 별도의 브랜치로 정리한 후 PR 보내주기 바랍니다. 커밋에 남겨둔 메시지들도 확인해주세요.

**Comment by namhyung** [comment]
Closed by PR #25
