### ISSUE TITLE
github 프로젝트에 CI 연동

### ISSUE THREAD

**Issue by namhyung** [swmaestro06-apus/apus#28]
travis 라던가 뭐든 github와 연동되는 CI 도구가 있으면 우리 프로젝트랑 연동해서 자동으로 빌드 및 테스트를 돌릴 수 있는 환경을 구축하면 좋겠습니다.

**Comment by jeongmincha** [comment]
제가 아는 선배한테 물어보니 
- TravisCI
- CircleCI
- Jenkins
  가 있다고 합니다.  

테스팅뿐만 아니라 빌드까지 자동화하는 도구라고 합니다.
빌드 통과 후에는 바로 릴리즈 가능한 바이너리를 만들거나,
웹 어플리케이션의 경우 서버로 바로 배포도 가능합니다.

**Comment by namhyung** [comment]
#35 에서 추가된 것으로는 단지 make를 실행하여 빌드 테스트 만을 하고 있는데, 이것과 별개로 make test를 실행하여 테스트 결과를 보여주는 것을 추가할 수 있으면 좋겠습니다.

**Comment by namhyung** [comment]
나중에 추가될 수 있는 기능이니 일단 닫겠습니다.
