### ISSUE TITLE
common 파일 안에 네임스페이스를 적용해야할것 같습니다.

### ISSUE THREAD

**Issue by enghqii** [swmaestro06-apus/apus#49]
apus.y 파일 안에서 Expression, Value, Statement 클래스들을 사용해 보기 위해, 아래와 같이 헤더파일을 include시켰습니다.

```
%code requires {
    #include <ast/value/value.h>
    #include <ast/expression.h>
}

%union {
    int64_t int_val;
    double double_val;
    int char_val;
    char* str_val;

    Expression* a;
}
```

그랬더니 빌드시 다음과 같은 오류가 발생합니다. 

```
[ 18%] Building CXX object src/CMakeFiles/apus.dir/lex.yy.cc.o
In file included from /Users/enghqii/Workspace/apus/src/apus.l:3:
y.tab.hh:62:5: error: redefinition of enumerator 'U8'
    U8 = 263,
    ^
/Users/enghqii/Workspace/apus/src/../include/common/common.h:16:9: note: previous definition is here
        U8, U16, U32, U64,  // Unsigned Integer
        ^
```

apus.y에서 %token부분에 U8, U16등의 타입관련 토큰에 대해 선언을 해 놓았기 때문에, yacc에 의해 만들어지는 파일인 y.tab.hh 헤더파일에 이 부분에 대한 선언부가 자동으로 생성됩니다.

common.h에 TypeSpecifier라는 enum안에 미리 U8, U16.. 등을 미리 정의해 놓아서 충돌이 일어난 것입니다.

```
// apus.y 파일
%token<int_val> U8 U16 U32 U64
%token<int_val> S8 S16 S32 S64
```

```
// 자동 생성된 y.tab.hh 파일
/* Token type.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
  enum yytokentype
  {
  .
  .
    U8 = 263,
    U16 = 264,
    U32 = 265,
    U64 = 266,
    S8 = 267,
    S16 = 268,
    S32 = 269,
    S64 = 270,
    F32 = 271,
    F64 = 272,
    C8 = 273,
    C16 = 274,
    C32 = 275,
    STR = 276,
    STR8 = 277,
    STR16 = 278,
    STR32 = 279,
.
.
  };
```

제 생각에는 common안에 있는 선언들을 apus나, apus::common등의 네임스페이스로 감싸는게 좋을것 같습니다.

**Comment by namhyung** [comment]
@JeongMinCha 제 생각에도 apus라는 namespace를 이용하는 것이 좋아보이네요..

**Comment by jeongmincha** [comment]
그런데, apus로 감싸더라도 저 에러는 계속 나더라구요...

**Comment by enghqii** [comment]
전 common 내용을 apus로 감싸고, BinaryReader의 선언, 정의, 사용부를 전부 apus네임스페이스를 사용하게 했더니 에러 안 났습니다

**Comment by jeongmincha** [comment]
아 근데 apus.y에서 #include"common/common.h"하면 에러가 나는겁니다

In file included from /Users/JeongMinCha/Dropbox/Development/apus/src/apus.y:5:
/Users/JeongMinCha/Dropbox/Development/apus/src/../include/common/common.h:17:9: error: expected identifier
        U8, U16, U32, U64,  // Unsigned Integer
        ^
/Users/JeongMinCha/Dropbox/Development/apus/src/y.tab.cc:154:12: note: expanded from macro 'U8'
#define U8 263
           ^
In file included from /Users/JeongMinCha/Dropbox/Development/apus/src/apus.y:5:

**Comment by jeongmincha** [comment]
직접적으로 헤더를 인크루드안하고 간접적으로 해도 저 에러 나네요

**Comment by enghqii** [comment]
전 apus.y파일 내부에서 직접, 간접 인클루드해도 에러 안 나던데 한번 봐야겠군요

2015-08-18 11:28 GMT+09:00 JeongMinCha notifications@github.com:

**Comment by jeongmincha** [comment]
넵 ㅠㅠㅠ 찬우형님 도와줍쇼

**Comment by namhyung** [comment]
Closed by #57
