### ISSUE TITLE
coding style 규칙 정하기

### ISSUE THREAD

**Issue by jeongmincha** [swmaestro06-apus/apus#5]
기본적으로 google c++ coding style 규칙으로 정하나, 이에 있어서 핵심적인 부분에 대해서 따로 위키에 정리해야 할 필요가 있으므로 coding style 규칙에 대해서 중요하고 빈번하게 마주하게 되는 부분에 대해서 작성할 것.

**Comment by namhyung** [comment]
기본적인 내용은 정리 완료
https://github.com/swmaestro06-apus/apus/wiki/%EC%BD%94%EB%94%A9-%EC%8A%A4%ED%83%80%EC%9D%BC

**Comment by enghqii** [comment]
코드를 작성하다가 모르는게 있으면 여길 참조하면 됩니다

https://github.com/swmaestro06-apus/apus/wiki/%EC%BD%94%EB%94%A9-%EC%8A%A4%ED%83%80%EC%9D%BC#spacing
