### ISSUE TITLE
Value: Promote 규칙을 변경해야 할 것같습니다.

### ISSUE THREAD

**Issue by enghqii** [swmaestro06-apus/apus#76]
기존에는 단순히 '같은 타입인지, 같은 클래스지만 사이즈만 다른건지, 아예 다른 클래스인지' 이렇게 세 가지 경우로 판단했는데, 이것보다 아래의 경우가 더 간단할것 같다고 생각합니다. 
1. (상대방이) 같은 타입일때는 변환하지 않는다.
2. 숫자 타입(Signed, Char, 그리고 앞으로 추가될 Unsigned 까지)과, 실수(Float) 타입이 만났을때는 무조건 실수 타입에 맞춘다.
3. 숫자 타입끼리 만났을 경우, 바이트 사이즈가 큰 데이터 타입으로 변환한다. (C32 + S8 => C32, C16 + S64 => S64) 
4. 어떤 타입이든 문자열 타입을 만날경우, 문자열로 변환한다.

위 규칙에 따르면 '문자열 > 실수형 > s정수 = u정수 = 문자' 와 같이, 타입 변환시 우선 순위가 자연스럽게 만들어질 것 같습니다.

**Comment by namhyung** [comment]
일단 문자열로 promotion 하는 것은 고려하지 않아도 될것 같구요. 필요하다면 나중에 구현할 수 있는 선택사항 정도일 것 같습니다. 제 생각에는 value promotion 보다 더 급하게 처리해야 할 일들을 찾아서 기본적인 구현을 완성하는 것이 우선이라고 판단됩니다.

**Comment by namhyung** [comment]
4번은 제외하고는 #90 에서 구현하였으므로 이 이슈는 일단 닫겠습니다.
